version: "3"
services:
  app:
    container_name: "ecoo-producer"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PACKAGE_JSON_PATH=./package.json
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
