version: "3"
services:
  producer_app:
    container_name: "ecoo_producer"
    build:
      context: ./producer
      dockerfile: ./Dockerfile
      args:
        - PACKAGE_JSON_PATH=./package.json
        - SHARED_SOURCE_PATH=../shared/src/
        - SHARED_TAILWIND_CONFIG_PATH=../shared/tailwind.config.ts
        - GET_FILES_SCRIPT_PATH=./get-external-files.ts
    ports:
      - "3001:3001"
    volumes:
      - ./shared/src/:/app/shared/src/
      - ./shared/tailwind.config.ts:/app/shared/tailwind.config.ts
      - ./producer/src:/app/src
      - ./producer/public:/app/public
      - ./producer/tsconfig.json:/app/tsconfig.json
      - ./producer/next.config.js:/app/next.config.js
      - ./producer/tailwind.config.ts:/app/tailwind.config.ts
      - ./producer/postcss.config.js:/app/postcss.config.js

  cdd_app:
    container_name: "ecoo_cdd"
    build:
      context: ./cdd
      dockerfile: ./Dockerfile
      args:
        - PACKAGE_JSON_PATH=./package.json
        - SHARED_SOURCE_PATH=../shared/src/
        - SHARED_TAILWIND_CONFIG_PATH=../shared/tailwind.config.ts
        - GET_FILES_SCRIPT_PATH=./get-external-files.ts
    ports:
      - "3002:3002"
    volumes:
      - ./shared/src/:/app/shared/src/
      - ./shared/tailwind.config.ts:/app/shared/tailwind.config.ts
      - ./cdd/src:/app/src
      - ./cdd/public:/app/public
      - ./cdd/tsconfig.json:/app/tsconfig.json
      - ./cdd/next.config.js:/app/next.config.js
      - ./cdd/tailwind.config.ts:/app/tailwind.config.ts
      - ./cdd/postcss.config.js:/app/postcss.config.js
